name: exchange-api-ci (kotlin)

on:
  pull_request:
    branches: [ main, develop ]

permissions:
    contents: read
    packages: write
    pull-requests: write
    issues: write

jobs:
  build-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Test
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build   

      - name: Copy Jar file
        run: cp build/libs/app.jar app.jar

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: app.jar

  build-docker-image:

    runs-on: ubuntu-latest
    needs: build-application

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jar-file
          path: app.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ls
        run: ls -la

#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: false
#          tags: brunomarins/ci-kotlin:latest
