name: exchange-api-ci (kotlin)

on:
  pull_request:
    branches: [ main, develop ]

permissions:
    contents: read
    packages: write
    pull-requests: write
    issues: write

jobs:
  build-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build   
      
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Package
      #     path: build/libs
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: false
      #     tags: brunomarins/ci-kotlin:latest
